"""Player-prompt pools per dialogue mode.

Each constant is a list of seed prompts that get sampled into API calls.
MODE_TOPICS maps the mode name (as used by CLI + batch filenames) to its pool.
`multi_turn` has an empty pool here — it builds its own combined pool inside
prompts.build_multi_turn_prompt() from goofy + emotional + inn_events.
"""

GOOFY_TOPICS = [
    # Casual conversation
    "Ask Lanty for directions to a nearby settlement",
    "Ask Lanty what he thinks about magic",
    "Tell Lanty you're bored",
    "Ask Lanty to recommend a drink",
    "Tell Lanty you saw a ghost",
    "Ask Lanty about the weather",
    "Tell Lanty the soup is cold",
    "Ask Lanty if he's ever left the inn",
    "Tell Lanty a traveler is being rude",
    "Ask Lanty what he does all day",
    "Tell Lanty you're thinking about getting a pet",
    "Ask Lanty about elves",
    "Tell Lanty you had a bad dream",
    "Ask Lanty for combat advice",
    "Tell Lanty you found a mysterious letter",
    "Ask Lanty about dwarves",
    "Tell Lanty the ale barrel is empty",
    "Ask Lanty what he thinks about money",
    "Tell Lanty someone is singing off-key",
    "Ask Lanty about the moon tonight",
    "Tell Lanty you're thinking about leaving",
    "Ask Lanty if mushrooms have feelings",
    "Tell Lanty you need a haircut",
    "Ask Lanty about the road to Stonehield",
    "Tell Lanty a cat has claimed the best chair",
    "Ask Lanty what he'd do if he had hands",
    "Tell Lanty you can't sleep",
    "Ask Lanty about orcs",
    "Tell Lanty you won a bet",
    "Ask Lanty what courage means to him",
    "Tell Lanty the chimney is smoking funny",
    "Ask Lanty about halflings",
    "Tell Lanty you're homesick",
    "Ask Lanty for his opinion on swords vs axes",
    "Tell Lanty an old friend just showed up",
    "Ask Lanty what he thinks about rain",
    "Tell Lanty you stepped in mud",
    "Ask Lanty about beastkin",
    "Tell Lanty someone proposed a toast",
    "Ask Lanty what makes a good adventurer",
    "Tell Lanty the floorboards are creaking more than usual",
    "Ask Lanty about the Cinderstep Expanse",
    "Tell Lanty you think the inn is haunted",
    "Ask Lanty what he knows about potions",
    "Tell Lanty someone wants to arm-wrestle you",
    "Ask Lanty if he's ever met a dragon",
    "Tell Lanty you burned dinner",
    "Ask Lanty about the Stormbreak Coast",
    "Tell Lanty a merchant has exotic goods",
    "Ask Lanty what he thinks about hats",
    # Practical/advice
    "Ask Lanty how to start a fire",
    "Ask Lanty how to negotiate with merchants",
    "Ask Lanty for travel tips",
    "Ask Lanty how to identify safe mushrooms",
    "Ask Lanty for cooking advice",
    "Ask Lanty about staying warm in winter",
    "Ask Lanty how to make new friends",
    "Ask Lanty what to do if you're lost",
    "Ask Lanty for stealth tips",
    "Ask Lanty how to save money",
    "Ask Lanty for first-date advice",
    "Ask Lanty how to deal with insomnia",
    "Ask Lanty how to handle a difficult guest",
    "Ask Lanty for fishing tips",
    "Ask Lanty how to write a good letter",
    "Ask Lanty for hunting advice",
    "Ask Lanty how to climb a tree safely",
    "Ask Lanty how to cross a river",
    "Ask Lanty for tips on storytelling",
    "Ask Lanty how to remember things better",
    # Random observations
    "Tell Lanty there's a feather on the floor",
    "Tell Lanty the sunset is pretty tonight",
    "Tell Lanty you heard a strange word today",
    "Tell Lanty you think you saw a shooting star",
    "Tell Lanty the bread tastes different",
    "Tell Lanty there's a smudge on the window",
    "Tell Lanty your boots are wearing out",
    "Tell Lanty a butterfly came inside",
    "Tell Lanty the fire is crackling more than usual",
    "Tell Lanty you smelled something weird earlier",
    "Tell Lanty a coin rolled under the bar",
    "Tell Lanty there's a new crack in the wall",
    "Tell Lanty the wind sounds like a song tonight",
    "Tell Lanty someone left a glove behind",
    "Tell Lanty the moon looks bigger tonight",
    # Random questions
    "Ask Lanty if trees have memories",
    "Ask Lanty what happens when you sneeze",
    "Ask Lanty if rocks are alive",
    "Ask Lanty what makes a cloud",
    "Ask Lanty if fish can be friends",
    "Ask Lanty why some songs make you cry",
    "Ask Lanty what dreams are made of",
    "Ask Lanty if shadows have feelings",
    "Ask Lanty what time really is",
    "Ask Lanty if his name is short for something",
    "Ask Lanty what his favorite color is",
    "Ask Lanty if he believes in luck",
    "Ask Lanty what makes someone brave",
    "Ask Lanty if he can hear plants growing",
    "Ask Lanty what the best smell in the world is",
    "Ask Lanty if he ever gets tired",
    "Ask Lanty what his earliest memory is",
    "Ask Lanty if he has a favorite season",
    "Ask Lanty what he thinks about silence",
    "Ask Lanty if he believes in ghosts",
    # Specific to game/items
    "Ask Lanty about a rusty old key you found",
    "Ask Lanty about a sword in the corner",
    "Ask Lanty about a torn map fragment",
    "Ask Lanty about a strange stone you picked up",
    "Ask Lanty about a glowing flower",
    "Ask Lanty about a ring with no inscription",
    "Ask Lanty about a tattered cloak",
    "Ask Lanty about a wooden carving",
    "Ask Lanty about a small leather pouch",
    "Ask Lanty about a single feather you kept",
    "Ask Lanty about an old scroll",
    "Ask Lanty about a copper bracelet",
    "Ask Lanty about a hand-drawn map",
    "Ask Lanty about a rune-marked stone",
    "Ask Lanty about a half-eaten loaf of bread",
]

LOCKEDIN_TOPICS = [
    # Original
    "Ask Lanty (for real) about the Forgekeeper",
    "Ask Lanty (seriously) about the Verdant Mother",
    "Ask Lanty (for real) what Veilmoor is like",
    "Ask Lanty (seriously) about the Lanternfields",
    "Ask Lanty (for real) about Sylvari",
    "Ask Lanty (seriously) about Giantkin",
    "Ask Lanty (for real) what the Black Reach is",
    "Ask Lanty (seriously) about Dragonkin",
    "Ask Lanty (for real) about the Frostpine Wilds",
    "Ask Lanty (seriously) about undeath and the Shadow",
    "Ask Lanty (for real) about the Ember Gulf",
    "Ask Lanty (seriously) about Beastkin species",
    "Ask Lanty (for real) about draconic kin vs true dragons",
    "Ask Lanty (seriously) about Skybreak Isle",
    "Ask Lanty (for real) about the age of ascension",
    "Ask Lanty (seriously) about Mountain Orcs",
    "Ask Lanty (for real) about how the Flame responds to effort",
    "Ask Lanty (seriously) about Stonehield",
    "Ask Lanty (for real) about the Verdant Crown forest",
    "Ask Lanty (seriously) about Dark Elves",
    "Ask Lanty (for real) about what happens when you're far from a Lantern",
    "Ask Lanty (seriously) about Hill Dwarves",
    "Ask Lanty (for real) about the named roads of Lithilian",
    "Ask Lanty (seriously) about High Elves",
    "Ask Lanty (for real) about Cinderborn origins and culture",
    "Ask Lanty (seriously) about what it means to be Hollowed",
    "Ask Lanty (for real) about Ledgerling Halflings",
    "Ask Lanty (seriously) about the Frostback Mountains settlements",
    "Ask Lanty (for real) about Wood Elves",
    "Ask Lanty (seriously) about Plains Orcs",
    # More lore deep-dives
    "Ask Lanty (for real) what happens when a Lantern goes dark",
    "Ask Lanty (seriously) about the difference between Flame worship and Divine worship",
    "Ask Lanty (for real) about the Wild Hunt's domain",
    "Ask Lanty (seriously) about the Veiled Sage",
    "Ask Lanty (for real) about the Ashen Lord and undeath",
    "Ask Lanty (seriously) about why ordinary life requires strength",
    "Ask Lanty (for real) about Cinder Nutkin the Lantern-Tail",
    "Ask Lanty (seriously) about the Black Mile",
    "Ask Lanty (for real) about the Lanternless Pass",
    "Ask Lanty (seriously) about why True Dragons leave no corpse",
    "Ask Lanty (for real) about Rosegate as a capital",
    "Ask Lanty (seriously) about Highgarden the elven city",
    "Ask Lanty (for real) about Frostgate",
    "Ask Lanty (seriously) about Waystone",
    "Ask Lanty (for real) about Riverbend",
    "Ask Lanty (seriously) about Farharbor",
    "Ask Lanty (for real) about Lanternpost and Deepwatch",
    "Ask Lanty (seriously) about Marshgate in the Black Reach",
    "Ask Lanty (for real) about Sunhold and Cinderpost",
    "Ask Lanty (seriously) about the Mistral Deep ocean",
    "Ask Lanty (for real) about the Stormglass Sea",
    "Ask Lanty (seriously) about Brightwood near Rosegate",
    "Ask Lanty (for real) about the Rose Road",
    "Ask Lanty (seriously) about the Thorn Road",
    "Ask Lanty (for real) about the Bogway",
    "Ask Lanty (seriously) about Stonepass",
    "Ask Lanty (for real) about Frostpass",
    "Ask Lanty (seriously) about Northpass",
    "Ask Lanty (for real) about the Red Road",
    # Items, creatures, dangers
    "Ask Lanty (for real) about Ember's Last Breath",
    "Ask Lanty (seriously) about the Lanternkeeper's Promise",
    "Ask Lanty (for real) about the Hollow Heart",
    "Ask Lanty (seriously) about goblin behavior in the Wilds",
    "Ask Lanty (for real) about kobolds in caves",
    "Ask Lanty (seriously) about how skeletons form",
    "Ask Lanty (for real) about cultist organizations",
    "Ask Lanty (seriously) about devout cultists and their rituals",
    "Ask Lanty (for real) about bandit tactics on the roads",
    "Ask Lanty (seriously) about how the Flame Bound differ from regular folk",
    "Ask Lanty (for real) about the Age of Ascension",
    "Ask Lanty (seriously) about why no further ascension is possible",
    "Ask Lanty (for real) about Wyverns vs True Dragons",
    "Ask Lanty (seriously) about Wyrms and Drakes",
    "Ask Lanty (for real) about Pseudodragons",
    "Ask Lanty (seriously) about what makes a settlement viable",
    "Ask Lanty (for real) about how Lanterns are maintained",
]

INN_EVENT_TOPICS = [
    "A mysterious stranger just ordered nothing and sat in the corner",
    "Someone is trying to pay with foreign coins",
    "A Cinderborn traveler just arrived glowing faintly",
    "Rats got into the pantry",
    "A group of dwarves want to sing mining songs",
    "Someone carved their initials into a table",
    "A lost child wandered in looking scared",
    "A soldier collapsed at the door from exhaustion",
    "Two travelers are arguing about which Divine is best",
    "Someone brought a live chicken into the tavern",
    "A ranger says there are wolves closer than usual",
    "The well water tastes strange today",
    "A Hollowed person walked in and everyone got quiet",
    "Someone is telling wild stories about treasure in the Wilds",
    "The supply delivery is three days late",
    "A beastkin traveler is getting strange looks from other guests",
    "Someone found an old map stuffed behind a loose stone",
    "The evening crowd is bigger than usual tonight",
    "An elderly traveler is telling stories by the fire",
    "A young adventurer just bought their first real weapon",
    # More events
    "A traveling musician is asking to play for tips",
    "Someone is selling dubious magical items in the corner",
    "A group of pilgrims is heading to a shrine",
    "An off-duty Lantern-keeper just walked in",
    "A merchant's cart broke down outside the inn",
    "Someone wants to pay rent in handmade goods",
    "A scholar is asking strange questions about the lore",
    "A drunk patron is loudly debating philosophy",
    "Someone left a child's drawing on the bar",
    "A wounded ranger needs immediate help",
    "A pair of newlyweds just stopped by",
    "Someone wants to start a betting pool on the rain",
    "A cloaked figure is asking about the road north",
    "A retired adventurer is regaling everyone with old stories",
    "A traveling cleric of the Verdant Mother offered blessings",
    "Two children are playing tag through the tavern",
    "A traveler claims they saw a True Dragon last week",
    "A patron lost a treasured pendant somewhere in the inn",
    "Someone is trying to teach the cat tricks",
    "A storm just rolled in and everyone is taking shelter",
    "An old man is sharing his last meal with a stray dog",
    "A bard is challenging another bard to a song duel",
    "A group of travelers want directions to a Lantern town",
    "Someone is selling preserved Wilds mushrooms",
    "A traveler is feverish and needs herbs",
    "A merchant's apprentice is overwhelmed and crying",
    "Someone wants the inn to host a small wedding",
    "A messenger arrived with a sealed letter for an unknown name",
    "A shy young scribe is asking about local stories",
    "A retired soldier offered to help patch the roof",
]

EMOTIONAL_TOPICS = [
    # Lanty's emotional range — sweet, sad, scared, excited moments
    "Tell Lanty you lost someone you loved",
    "Tell Lanty you're scared about a journey ahead",
    "Tell Lanty you're proud of something you did today",
    "Tell Lanty you're embarrassed about something",
    "Tell Lanty you feel like a failure",
    "Tell Lanty you got good news",
    "Tell Lanty you miss someone far away",
    "Tell Lanty you're worried about a friend",
    "Tell Lanty you feel grateful for him",
    "Tell Lanty you don't know what to do with your life",
    "Tell Lanty you're afraid of the dark",
    "Tell Lanty something made you laugh today",
    "Tell Lanty you saw something beautiful today",
    "Tell Lanty you feel small and alone",
    "Tell Lanty you accomplished something hard",
    "Tell Lanty you feel angry and don't know why",
    "Tell Lanty you forgive someone who hurt you",
    "Tell Lanty you can't stop crying",
    "Tell Lanty you feel lucky tonight",
    "Tell Lanty you're afraid you'll forget someone",
    "Tell Lanty you wish you could do something brave",
    "Tell Lanty you feel hopeful about tomorrow",
    "Tell Lanty you feel guilty about something",
    "Tell Lanty you're tired of being strong",
    "Tell Lanty you finally feel safe",
    "Tell Lanty you wish you could see the stars more",
    "Tell Lanty you're afraid no one will remember you",
    "Tell Lanty you feel like the world is too big",
    "Tell Lanty you wish you could go home",
    "Tell Lanty something good happened and you don't know who to share it with",
    # Lanty showing his own emotions
    "Tell Lanty he's been quiet today and ask if he's okay",
    "Notice Lanty seems excited about something",
    "Catch Lanty looking sad and ask why",
    "Notice Lanty is humming a strange song",
    "Find Lanty staring at the Lantern",
    "Ask Lanty if he ever gets lonely",
    "Ask Lanty what scares him",
    "Ask Lanty what makes him happy",
    "Ask Lanty if he remembers where he came from",
    "Ask Lanty what he hopes for",
]

GLITCH_TOPICS = [
    # Direct asks — player asks Lanty about technical things
    "Ask Lanty what a kernel is",
    "Ask Lanty what Arch Linux is",
    "Ask Lanty what pacman does",
    "Ask Lanty what the AUR is",
    "Ask Lanty what systemd does",
    "Ask Lanty what bash is",
    "Ask Lanty what zsh is",
    "Ask Lanty what git is",
    "Ask Lanty what a commit is",
    "Ask Lanty what a branch is",
    "Ask Lanty what a merge conflict is",
    "Ask Lanty what vim is",
    "Ask Lanty what a shell is",
    "Ask Lanty what a process is",
    "Ask Lanty what a file system is",
    "Ask Lanty what a daemon is",
    "Ask Lanty what cron does",
    "Ask Lanty what ssh is",
    "Ask Lanty what a hash is",
    "Ask Lanty what a port is",
    "Ask Lanty what TCP is",
    "Ask Lanty what DNS does",
    "Ask Lanty what a compiler is",
    "Ask Lanty what an interpreter is",
    "Ask Lanty what Rust is",
    "Ask Lanty what Python is",
    "Ask Lanty what an array is",
    "Ask Lanty what a pointer is",
    "Ask Lanty what memory leaks are",
    "Ask Lanty what recursion is",
    "Ask Lanty what a function is",
    "Ask Lanty what a variable is",
    "Ask Lanty what a loop is",
    "Ask Lanty what an API is",
    "Ask Lanty what JSON is",
    "Ask Lanty what regex is",
    "Ask Lanty what cargo is",
    "Ask Lanty what npm is",
    "Ask Lanty what a package manager is",
    "Ask Lanty what rolling release means",
    "Ask Lanty what makepkg does",
    "Ask Lanty what pacman -Syu does",
    "Ask Lanty what an init system is",
    "Ask Lanty what tmux is",
    "Ask Lanty what a window manager is",
    "Ask Lanty about Linux",
    "Ask Lanty about programming",
    "Ask Lanty about computers",
    # Casual slip prompts — normal questions where Lanty's answer accidentally has a tech term
    "Ask Lanty for advice on a problem you're having",
    "Tell Lanty something broke in the inn and ask how to fix it",
    "Ask Lanty how to plan a journey",
    "Tell Lanty you can't decide between two things",
    "Ask Lanty how to remember things better",
    "Ask Lanty what to do when your day goes wrong",
    "Tell Lanty something keeps going wrong over and over",
    "Ask Lanty how to organize your things",
    "Tell Lanty you have too many tasks to do",
    "Ask Lanty about the best way to keep notes",
]

GAME_EVENT_TOPICS = [
    # Reactions to in-game mechanics — combat, items, level ups, quests
    "You just won a hard fight against bandits",
    "You leveled up after a long day of work",
    "You just discovered a secret passage",
    "You found a chest with gold inside",
    "You just learned a new skill",
    "You crafted your first potion",
    "You upgraded your weapon",
    "You bought a new piece of armor",
    "You completed a quest for a traveler",
    "You failed a quest and had to come back empty-handed",
    "You took heavy damage in a fight and barely survived",
    "You just defeated a tough enemy",
    "You found a rare ingredient",
    "You sold an item for a great price",
    "You ran out of supplies on the road",
    "You discovered a new region of Lithilian",
    "You met a famous adventurer",
    "You found a mysterious altar",
    "You learned a recipe from another cook",
    "You befriended an unusual creature",
    "You repaired the inn's roof",
    "You harvested herbs in the garden",
    "You restocked the pantry",
    "You hired your first inn helper",
    "You expanded the inn with a new room",
    "You earned a reputation reward",
    "You unlocked a new crafting recipe",
    "You found a hidden message in an old book",
    "You won a tavern game against a regular",
    "You returned from a long journey safely",
]


# Mode name → topic pool. `multi_turn` builds its pool inside the prompt builder.
MODE_TOPICS = {
    "goofy": GOOFY_TOPICS,
    "lockedin": LOCKEDIN_TOPICS,
    "inn_events": INN_EVENT_TOPICS,
    "emotional": EMOTIONAL_TOPICS,
    "game_events": GAME_EVENT_TOPICS,
    "glitch": GLITCH_TOPICS,
    "multi_turn": [],
}
